# Ruta raíz donde se almacenarán los artefactos generados
artifacts_root: artifacts

# Configuración para la ingesta de datos
data_ingestion:
  # Directorio raíz para los artefactos de ingesta de datos
  root_dir: artifacts/data_ingestion
  
  # URL de la fuente desde donde se descargará el archivo de datos
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip 
  
  # Ruta local donde se almacenará el archivo de datos descargado
  local_data_file: artifacts/data_ingestion/data.zip
  
  # Directorio donde se descomprimirá el archivo de datos
  unzip_dir: artifacts/data_ingestion

#
data_validation:
  root_dir: artifacts/data_validation
  #el archivo a valdiar con los datos unzipeados
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#aqui hay split pero en la clase hay que incluir todas las etapas de preprocesado
data_transformation:
  root_dir: artifacts/data_transformation
  #el archivo para empezar las tranformaciones
  data_path: artifacts/data_ingestion/winequality-red.csv

#
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

  


